### PR TITLE
feat:single product page added

### PR DESCRIPTION
**Pull request by JowelTisso**
This PR is single product page

### CODE REVIEW

**Review by Nishant-96 — APPROVED** [review]
Everything looks good.
-like the namings.
-good file structure.

**Review by sanjitsarkar — APPROVED** [review]
Proper use of utility classes and Code is clean and easy to readable.
Good to merge

**Review by Mandhularajitha — APPROVED** [review]
Code is clean Looks Good

**Review by NtshVrm — APPROVED** [review]
No suggestions in particular
- Consistent Naming Convention
- Very Readable Code

**Pull request merged**
